"""
LastWarIntel
Assessment Models
Version: 1.0

Universal assessment models.

Every interpretation inside LastWarIntel should eventually be represented
as an Assessment backed by Evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from analytics.events.models import EntityType


# ----------------------------------------------------------------------
# Assessment Types
# ----------------------------------------------------------------------


class AssessmentType(Enum):
    ALLIANCE_HEALTH = "Alliance Health"
    RECRUITMENT = "Recruitment"
    SERVER_DNA = "Server DNA"
    STABILITY = "Server Stability"
    GROWTH = "Growth"
    PLAYER_STRENGTH = "Player Strength"
    PREDICTION = "Prediction"


# ----------------------------------------------------------------------
# Evidence
# ----------------------------------------------------------------------


@dataclass(slots=True)
class Evidence:
    """
    One piece of evidence supporting an assessment.

    Evidence is always traceable back to facts or events.
    """

    source: str
    title: str
    explanation: str

    weight: float = 0.0
    confidence: float = 100.0

    metadata: dict[str, Any] = field(default_factory=dict)


# ----------------------------------------------------------------------
# Assessment
# ----------------------------------------------------------------------


@dataclass(slots=True)
class Assessment:
    """
    Universal assessment object.

    Every interpretation generated by LastWarIntel should use this model.
    """

    assessment_type: AssessmentType

    entity_type: EntityType
    entity: str

    score: float
    confidence: float

    summary: str

    evidence: list[Evidence] = field(default_factory=list)

    metadata: dict[str, Any] = field(default_factory=dict)

    @property
    def evidence_score(self) -> float:
        return sum(item.weight for item in self.evidence)

    @property
    def evidence_count(self) -> int:
        return len(self.evidence)

    @property
    def strongest_evidence(self) -> Evidence | None:
        if not self.evidence:
            return None

        return max(self.evidence, key=lambda item: item.weight)