from pathlib import Path
import pandas as pd


def export(grouped, filename="output/lastwar_export.xlsx"):

    output = Path(filename)
    output.parent.mkdir(exist_ok=True)

    with pd.ExcelWriter(output, engine="openpyxl") as writer:

        for (server, ranking_type), rows in grouped.items():

            df = pd.DataFrame(rows)

            if df.empty:
                continue

            if ranking_type == "total_hero_power":
                preferred_columns = [
                    "rank",
                    "ocr_rank",
                    "computed_rank",
                    "rank_warning",
                    "pending_review",
                    "pending_review_reason",
                    "rank_slot_preserved",
                    "observed_name",
                    "normalized_name",
                    "canonical_name",
                    "observed_alliance",
                    "normalized_alliance",
                    "canonical_alliance",
                    "alliance_tag",
                    "player_name",
                    "name",
                    "power",
                    "power_original",
                    "power_recovered_from",
                    "power_recovery_method",
                    "power_recovery_status",
                    "power_sanity_status",
                    "power_sanity_confidence",
                    "power_candidate_count",
                    "power_candidate_best",
                    "power_candidate_best_score",
                    "power_candidate_second",
                    "power_candidate_second_score",
                    "power_candidate_margin",
                    "power_recovery_selected_reason",
                    "power_recovery_decision_strategy",
                    "power_recovery_decision_version",
                    "power_recovery_legacy_used",
                    "power_recovery_candidates",
                    "review_ocr_attempted",
                    "review_ocr_status",
                    "review_ocr_variants",
                    "review_ocr_candidate_count",
                    "review_ocr_best_variant",
                    "review_ocr_score",
                    "review_ocr_decision",
                    "review_ocr_reasons",
                    "row_reconstruction_attempted",
                    "row_reconstruction_status",
                    "row_reconstruction_score",
                    "row_reconstruction_reason",
                    "row_reconstruction_anchor_before_power",
                    "row_reconstruction_anchor_after_power",
                    "row_reconstruction_rank",
                    "row_reconstruction_method",
                    "row_reconstruction_candidate_margin",
                    "row_reconstruction_candidate_count",
                    "digit_preservation_score",
                    "confidence",
                    "parse_status",
                    "parse_warnings",
                    "parse_corrections",
                    "normalized_identity",
                    "server_confidence",
                    "server_source",
                    "server_warning",
                    "data_guard_conflict",
                    "raw_text",
                    "source_file",
                ]
            elif ranking_type in {"server_review", "data_guard_quarantine", "ranking_guard_quarantine"}:
                preferred_columns = [
                    "source_file",
                    "ranking_type",
                    "original_ranking_type",
                    "expected_ranking_type",
                    "ranking_guard_status",
                    "ranking_guard_confidence",
                    "ranking_guard_reason",
                    "ranking_guard_warning",
                    "original_server",
                    "candidate_server",
                    "server",
                    "rank",
                    "ocr_rank",
                    "computed_rank",
                    "rank_warning",
                    "pending_review",
                    "pending_review_reason",
                    "rank_slot_preserved",
                    "observed_name",
                    "normalized_name",
                    "canonical_name",
                    "observed_alliance",
                    "normalized_alliance",
                    "canonical_alliance",
                    "alliance_tag",
                    "player_name",
                    "name",
                    "power",
                    "power_original",
                    "power_recovered_from",
                    "power_recovery_method",
                    "power_recovery_status",
                    "power_sanity_status",
                    "power_sanity_confidence",
                    "power_candidate_count",
                    "power_candidate_best",
                    "power_candidate_best_score",
                    "power_candidate_second",
                    "power_candidate_second_score",
                    "power_candidate_margin",
                    "power_recovery_selected_reason",
                    "power_recovery_decision_strategy",
                    "power_recovery_decision_version",
                    "power_recovery_legacy_used",
                    "power_recovery_candidates",
                    "review_ocr_attempted",
                    "review_ocr_status",
                    "review_ocr_variants",
                    "review_ocr_candidate_count",
                    "review_ocr_best_variant",
                    "review_ocr_score",
                    "review_ocr_decision",
                    "review_ocr_reasons",
                    "row_reconstruction_attempted",
                    "row_reconstruction_status",
                    "row_reconstruction_score",
                    "row_reconstruction_reason",
                    "row_reconstruction_anchor_before_power",
                    "row_reconstruction_anchor_after_power",
                    "row_reconstruction_rank",
                    "row_reconstruction_method",
                    "row_reconstruction_candidate_margin",
                    "row_reconstruction_candidate_count",
                    "digit_preservation_score",
                    "server_confidence",
                    "server_source",
                    "server_warning",
                    "data_guard_conflict",
                    "quarantine_reason",
                    "quarantine_candidate_server",
                    "server_detections",
                    "ocr_elements",
                    "raw_text",
                ]
            else:
                preferred_columns = [
                    "rank",
                    "ocr_rank",
                    "computed_rank",
                    "rank_warning",
                    "pending_review",
                    "pending_review_reason",
                    "rank_slot_preserved",
                    "observed_name",
                    "normalized_name",
                    "canonical_name",
                    "observed_alliance",
                    "normalized_alliance",
                    "canonical_alliance",
                    "name",
                    "power",
                    "power_original",
                    "power_recovered_from",
                    "power_recovery_method",
                    "power_recovery_status",
                    "power_sanity_status",
                    "power_sanity_confidence",
                    "power_candidate_count",
                    "power_candidate_best",
                    "power_candidate_best_score",
                    "power_candidate_second",
                    "power_candidate_second_score",
                    "power_candidate_margin",
                    "power_recovery_selected_reason",
                    "power_recovery_decision_strategy",
                    "power_recovery_decision_version",
                    "power_recovery_legacy_used",
                    "power_recovery_candidates",
                    "review_ocr_attempted",
                    "review_ocr_status",
                    "review_ocr_variants",
                    "review_ocr_candidate_count",
                    "review_ocr_best_variant",
                    "review_ocr_score",
                    "review_ocr_decision",
                    "review_ocr_reasons",
                    "row_reconstruction_attempted",
                    "row_reconstruction_status",
                    "row_reconstruction_score",
                    "row_reconstruction_reason",
                    "row_reconstruction_anchor_before_power",
                    "row_reconstruction_anchor_after_power",
                    "row_reconstruction_rank",
                    "row_reconstruction_method",
                    "row_reconstruction_candidate_margin",
                    "row_reconstruction_candidate_count",
                    "digit_preservation_score",
                    "server_confidence",
                    "server_source",
                    "server_warning",
                    "data_guard_conflict",
                    "source_file",
                    "raw_text",
                ]

            columns = [column for column in preferred_columns if column in df.columns]
            df = df[columns]
            for column in ("power_recovery_candidates", "server_detections", "ocr_elements"):
                if column in df.columns:
                    df[column] = df[column].apply(lambda value: str(value) if value not in (None, "") else "")

            sheet = f"{server}_{ranking_type}"

            df.to_excel(
                writer,
                sheet_name=sheet[:31],
                index=False
            )

    print(f"\nExcel geschrieben nach {output}")